### ISSUE TITLE
Pattern printing in c++

### ISSUE THREAD

**Issue by lakshyabatman** [lakshyabatman/algorithms-stew#10]
Please use this thread to post related to pattern printing in C++!

Refer from the internet and show your creativity to make patterns! :D

**Comment by hotshott22** [comment]
hey, I'm interested in solving this issue can you please elaborate what to do, I'm new to open sources but good at coding (4* on CodeChef )

**Comment by dk5ee** [comment]
made one: #14 
I did not know if "using namespace std;" is good or bad practice here.

**Comment by lakshyabatman** [comment]
@prashikpatil221 That's dope! I created this repo so I can push code while learning DSA, you can add basic printing code here, or take on add any of your choice code related to graph or trees which doesn't exist in the repo. :D 
@dk5ee can you share the screenshot of the pattern please and it's okay to `using namespace std` here.

**Comment by dk5ee** [comment]
@prashikpatil221 added screenshots in #14

**Comment by Mayankjha997** [comment]
hey, I'm interested in solving this issue can you please elaborate what to do, I'm new to open sources but good at coding.

**Comment by lakshyabatman** [comment]
@Mayankjha997 ahh that's great, try out building a pattern using C++/Python in their respective folder and make sure to share a screenshot of pattern here so duplicates can be avoided. 👍 

**Pattern can be any of your choice**, like pyramid or star one.

**Comment by Mayankjha997** [comment]
It will get added up in hacktoberfest ot not??

**Comment by lakshyabatman** [comment]
@Mayankjha997  Yes! Any public GitHub repository is good for Hacktoberfest.
https://hacktoberfest.digitalocean.com/faq please look over it as well.

**Comment by kratikaatgithub** [comment]
@lakshyabatman I am new to contributing to open source. I have a question, if someone creates a PR before me on a certain issue, will I not be allowed to make a PR of my own?

**Comment by lakshyabatman** [comment]
@kratikaatgithub , basically what happens the person who asks to assign an issue to themselves is assigned and he/she works on it, but here it is open to everyone, that's why I mentioned sharing what pattern the contributor will be building to avoid clashes and if in case it happens the open who sent PR first will be considered but I don't think that'll happen. 👍

**Comment by kratikaatgithub** [comment]
Thanks @lakshyabatman for the help.
