### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by rrachitgarg** [lakshyabatman/algorithms-stew#6]
There is a spelling mistake in your contributing guidelines. Please fix it ASAP.
Thank you.

**Comment by Vansh1067** [comment]
Can I work on this and open the PR during Hacktoberfest? :)

**Comment by rrachitgarg** [comment]
@Vansh1067 Yes sure.

**Comment by lakshyabatman** [comment]
The issue is fixed, thanks @Vansh1067
