### ISSUE TITLE
Contributing guide is not properly written

### ISSUE THREAD

**Issue by lakshyabatman** [lakshyabatman/algorithms-stew#7]
It's sucks, but I wasn't able to write a good contributing guide properly!

Please make sure it:
- It explains how to clone the repo.
- How to run C++ or Python file using the terminal.
- How to use launch and tasks configs for vs code.
- How to commit changes!
- How to send a Pull Request!

**Comment by Manoj13-coder** [comment]
Assign this task to me i will make all important changes that you require

**Comment by lakshyabatman** [comment]
Sure! As you can see contributing guide should include how it get started with git, how to write proper pull request message, how to compile or run C++/Python, describe writing comments in code!  That'll be fine for now :D

**Comment by Manoj13-coder** [comment]
Thank you
