### ISSUE TITLE
Graph class and basic graph traversal is not in written

### ISSUE THREAD

**Issue by lakshyabatman** [lakshyabatman/algorithms-stew#8]
So, I've switched to c++ for DSA, So never got to play around with graphs in python.

- Need a graph class file so it can be reused.
- A basic DFS/BFS traversal in another file.

** Make sure to make two separates files **.

**Comment by Manoj13-coder** [comment]
can you please tell me more about graph class file?

**Comment by Manoj13-coder** [comment]
what is it?

**Comment by lakshyabatman** [comment]
Sure bud, So basically while doing Graph related questions, I already kept a graph class file which can be used so writing same code and code can be avoided, for example, look over C++/Graphs I already created A Graph.h there.

- For python, you only need to make a class for a directed unweighted graph using adj list, which can be used while doing graph related questions in python also make sure to add addEdge method in it to add vertices/edges. :D

**Comment by debangeedas** [comment]
Hey! If this issue is still not assigned I would like to give it a shot. Please clarify whether I should go ahead with it.

**Comment by lakshyabatman** [comment]
@Manoj13-coder are you working on it?

**Comment by debangeedas** [comment]
> @Manoj13-coder are you working on it?

Please consider assigning it to me

**Comment by Manoj13-coder** [comment]
you will contribute

**Comment by abhhii** [comment]
Hey @lakshyabatman can I work on this?
