### ISSUE TITLE
Pattern printing in Python

### ISSUE THREAD

**Issue by lakshyabatman** [lakshyabatman/algorithms-stew#9]
Please use this thread to post related to pattern printing in python!

- Refer from the internet and show your creativity to make patterns! :D

**Comment by DeepaPrasanna** [comment]
Should I have to include pattern related programming ques in that folder?

**Comment by DEBANJANAB** [comment]
Hey, I am interested to work on this. Can you explain whether I will have to form new questions on pattern printing and solve them or just add questions?

**Comment by lakshyabatman** [comment]
@DeepaPrasanna , Yes there is a folder in Python.
@DEBANJANAB You have to write for basic pattern printing, please add what pattern code you'll be adding with a screenshot of it to avoid duplicates. :D

**Comment by Vrindagupta6828** [comment]
Hey are you talking about pyramid star patterns? and where we have to upload the picture in a separate file in the same folder as pattern printing and what type of file it has to be?

**Comment by lakshyabatman** [comment]
Hey @Vrindagupta6828 , you have t upload it here so someone who is new can see what patterns are already made.

**Comment by lakshyabatman** [comment]
Pyramid or star or any pattern you've done or wanna try. Pattern building is a good excerise for beginners who're new in programming right? :D

**Comment by Vrindagupta6828** [comment]
Hey are you talking about pyramid star patterns? and where we have to upload the picture in a separate file in the same folder as pattern printing and what type of file it has to be?

> Hey @Vrindagupta6828 , you have t upload it here so someone who is new can see what patterns are already made.

here where in a new jpg file in the pattern printing folder?

**Comment by lakshyabatman** [comment]
Here as in, in the issue thread, you can upload any picture file here. 
There is a image icon in a markdown editor to add image.

**Comment by Nagasandesh** [comment]
Hey @lakshyabatman , I am interested to work on this. Can I contribute?

**Comment by Vrindagupta6828** [comment]
Okay and thank you @lakshyabatman

**Comment by DeepaPrasanna** [comment]
I am too interested in this. Can I contribute :) ?

**Comment by lakshyabatman** [comment]
@DeepaPrasanna sure everyone is welcome 👍

**Comment by Vrindagupta6828** [comment]
Why is this issue closed?

**Comment by Vrindagupta6828** [comment]
It will not be counted in hacktober fest?
